In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [ ]:
x= np.arange(-10,10).reshape(-1,1)
x

array([[-10],
       [ -9],
       [ -8],
       [ -7],
       [ -6],
       [ -5],
       [ -4],
       [ -3],
       [ -2],
       [ -1],
       [  0],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [ ]:
y=np.where(x>0,1,0).reshape(-1)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
model= LogisticRegression().fit(x,y)

In [ ]:
model.predict(np.array([[-21],[-30],[11],[15]]))

array([0, 0, 1, 1])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
x= np.arange(1,11).reshape(-1,1)
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
y=np.array(x*2).reshape(-1)
y

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
model= LinearRegression().fit(x,y)
model.predict(np.array([[11],[12]]))

array([22., 24.])