In [ ]:
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
iris = load_iris()
x = iris.data
y = iris.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Input(shape=(4,)),
  tf.keras.layers.Dense(10, activation="relu"),
  tf.keras.layers.Dense(8, activation="relu"),
  tf.keras.layers.Dense(3, activation = "softmax") #Salida de 3 probabilidades mediante SOFTMAX
])

In [ ]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [ ]:
early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="loss",
    patience=3,
    restore_best_weights=True)

In [ ]:
model.fit(x_train, y_train, epochs=500, callbacks=[early_stop])

Epoch 1/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8917 - loss: 0.2857
Epoch 2/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8917 - loss: 0.2837
Epoch 3/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8917 - loss: 0.2817
Epoch 4/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8917 - loss: 0.2796 
Epoch 5/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8917 - loss: 0.2778
Epoch 6/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8917 - loss: 0.2757
Epoch 7/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9000 - loss: 0.2736
Epoch 8/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9083 - loss: 0.2718
Epoch 9/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9083 - loss: 0.2697
Epoch 10/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9000 - loss: 0.2678
Epoch 11/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9083 - loss: 0.2660
Epoch 12/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9083 - l

In [ ]:
predicciones = model.predict(x_test).argmax(1)
print("Predicciones del modelo")
print(predicciones)
print("Etiquetas reales de los datos des prueba")
print(y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step
Predicciones del modelo
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Etiquetas reales de los datos des prueba
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [ ]:
print("---Métricas de evaluación del modelo---")
print(classification_report(y_test, predicciones))


---Métricas de evaluación del modelo---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
print("---Métricas de evaluación del modelo---")
print("Matriz de confusión")
print(confusion_matrix(y_test, predicciones))
print("Precisión del modelo")

---Métricas de evaluación del modelo---
Matriz de confusión
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Precisión del modelo
